# Andrew Bear
# CS325 Homework 8
# Puzzle Solver Portfolio
# This borrows heavily from the techniques used in my MinPuzzle solution -- Dijkstra with some extra steps

import heapq


def solve_puzzle(Board, Source, Destination):
    """
    Function returns a minimum-effort path from Source to Destination through a maze.
    :param Board: Puzzle to analyze
    :param Source: Source sqare in (x, y) format
    :param Destination: Destination Square in (x, y) format
    :return: [[path of nodes], string of U/D/L/R moves]
    """

    # call the function that populates the effort dictionary
    effort_dic = calculate_effort(Board, Source, Destination)

    # if there is no dictionary, no path so return None
    if not effort_dic:
        return None

    # call the trace function
    path = create_trace(effort_dic, Source, Destination)

    # huzzah
    return path


def calculate_effort(Board, Source, Destination):
    """
    Returns minimum effort dictionary generated during traversal from the
    Source to Destination nodes of the puzzle.
    :param Board: puzzle to be solved
    :return: dictionary of nodes and the effort required to reach them
    """
    # length and height
    length = len(Board)
    height = len(Board[0])

    # populate effort dictionary with infinitys
    efforts = dict()
    for i in range(length):
        for j in range(height):
            efforts[(i, j)] = float("infinity")

    # overwrite effort of starting node
    efforts[Source[0], Source[1]] = 0

    # start priority queue, with 0 effort and coords of the Source
    pq = [(0, (Source[0], Source[1]))]

    # here be a standard-ish Djikstra loop, with a few caveats
    while len(pq) > 0:
        current_effort, current_vertex = heapq.heappop(pq)

        # skip this, because it's a bad path
        if current_effort > efforts[current_vertex]:
            continue

        # return current dictionary if we reach Destination node
        if current_vertex == (Destination[0], Destination[1]):
            return efforts

        # generate list of adjacent neighbors, and effort values (aka the edges)
        neighbors = _adjacent_elements(Board, current_vertex[0], current_vertex[1])

        # step through the neighbors of the current location
        for neighbor, effort in neighbors:
            # min effort to reach neighbor is current +1 (all edges are the same cost)
            min_eff = current_effort + 1

            # test, update, push neighbor
            if min_eff < efforts[neighbor]:
                efforts[neighbor] = min_eff
                heapq.heappush(pq, (min_eff, neighbor))


def create_trace(effort, source, dest):
    """
    Function that creates the move traces through the puzzle,
    given an effort dictionary and the source and destination
    :param effort: effort dictionary generated by calculate_effort
    :param source: Source node
    :param dest:  Destination node
    :return: tuple, where first element is list of nodes visited, and the second element
    is a string of U/D/L/R directions that correspond to the motions to generate the path
    """

    # setup
    moves = []
    visited = []
    cur_node = dest
    cur_eff = effort[dest]

    # loop walks backwards, adding letters and tuples to the lists
    while cur_eff > 0:
        visited.append(cur_node)
        cur_eff -= 1

        if (cur_node[0] - 1, cur_node[1]) in effort and effort[(cur_node[0] - 1, cur_node[1])] == cur_eff:
            moves.append("D")
            cur_node = (cur_node[0] - 1, cur_node[1])
        elif (cur_node[0] + 1, cur_node[1]) in effort and effort[(cur_node[0] + 1, cur_node[1])] == cur_eff:
            moves.append("U")
            cur_node = (cur_node[0] + 1, cur_node[1])
        elif (cur_node[0], cur_node[1] - 1) in effort and effort[(cur_node[0], cur_node[1] - 1)] == cur_eff:
            moves.append("R")
            cur_node = (cur_node[0], cur_node[1] - 1)
        elif (cur_node[0], cur_node[1] + 1) in effort and effort[(cur_node[0], cur_node[1] + 1)] == cur_eff:
            moves.append("L")
            cur_node = (cur_node[0], cur_node[1] + 1)

    # stringify the list of letters
    movstring = ""
    for i in range(len(moves)-1, -1, -1):
        movstring += moves[i]

    # add source node and reverse
    visited.append(source)
    visited.reverse()

    return visited, movstring


def _is_valid_position(x, y, width, height, puzzle):
    """
    Checks if element x, y is valid position in the 2d array
    :param x: desired x
    :param y: desired y
    :param width: width of array
    :param height: height of array
    :return: 0 if invalid location, 1 if valid location in array
    """
    if x < 0 or y < 0 or x > width - 1 or y > height - 1 or puzzle[x][y] == "#":
        return 0
    return 1


def _adjacent_elements(puzzle, x, y):
    """
    Returns a list of the adjacent elements to a given x, y, in the puzzle, along with the effort required to reach
    each neighbor
    :param puzzle: puzzle array
    :param x: x coordinate
    :param y: y coordinate
    :return: list of neighbors, each in the form [(x,y), 1]
    """
    # Size of given 2d array
    n = len(puzzle)
    m = len(puzzle[0])

    # result list
    results = []

    # Checking for all the possible adjacent positions; adding to results if they are
    # Appends [(x, y), effort] for each allowable neighbor
    if _is_valid_position(x - 1, y, n, m, puzzle):
        results.append([(x-1, y), 1])
    if _is_valid_position(x + 1, y, n, m, puzzle):
        results.append([(x+1, y), 1])
    if _is_valid_position(x, y - 1, n, m, puzzle):
        results.append([(x, y-1), 1])
    if _is_valid_position(x, y + 1, n, m, puzzle):
        results.append([(x, y+1), 1])

    # done
    return results


# # Testing section
# Puzzle = [
#     ['-', '-', '-', '-', '-'],
#     ['-', '-', '#', '-', '-'],
#     ['-', '-', '-', '-', '-'],
#     ['#', '-', '#', '#', '-'],
#     ['-', '#', '-', '-', '-']
#     ]
#
# print(solve_puzzle(Puzzle, (0,0), (4,4)))
#
# Puzzle = [
#     ['-', '-', '-', '-', '-'],
#     ['-', '-', '#', '-', '-'],
#     ['-', '-', '-', '-', '-'],
#     ['#', '-', '#', '#', '-'],
#     ['-', '#', '-', '-', '-']
#     ]
#
# print(solve_puzzle(Puzzle, (4,0), (4,4)))
#
# Puzzle = [
#     ['-', '-', '-', '-', '-'],
#     ['-', '-', '#', '-', '-'],
#     ['-', '-', '-', '-', '-'],
#     ['#', '-', '#', '#', '-'],
#     ['-', '#', '-', '-', '-']
#     ]
#
# print(solve_puzzle(Puzzle, (0,2), (2,2)))
#
# Puzzle = [
#     ['-', '#', '-', '-', '-'],
#     ['-', '#', '-', '#', '-'],
#     ['-', '#', '-', '#', '-'],
#     ['-', '#', '-', '#', '-'],
#     ['-', '-', '-', '#', '-']
#     ]
#
# print(solve_puzzle(Puzzle, (0,0), (4,4)))